### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kroscek** [chrischoy/knn_cuda#2]
I'm using Anaconda2 and gcc 4.8 version. Make compiling generates error, not sure what happens:

/usr/bin/g++ -fPIC  -DNDEBUG -O2 -I/home/lemma/anaconda2/include -I/home/lemma/anaconda2/include/python2.7 -I/home/lemma/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/home/lemma/anaconda2/include -I/home/lemma/anaconda2/include/python2.7 -I/home/lemma/anaconda2/lib/python2.7/site-packages/numpy/core/include -I./src -I/usr/local/cuda/include  -c src/knn.cpp -o build/knn.o
In file included from /home/lemma/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/lemma/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from src/knn.cpp:3:
/home/lemma/anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
src/knn.cpp: In function 'boost::python::api::object extract_feature(PyObject*, PyObject*)':
src/knn.cpp:54:3: error: 'numeric' has not been declared
   numeric::array arr(handle);
   ^
src/knn.cpp:59:10: error: 'arr' was not declared in this scope
   return arr.copy();
          ^
src/knn.cpp: In function 'boost::python::api::object knn(PyObject*, PyObject*, int)':
src/knn.cpp:99:3: error: 'numeric' has not been declared
   numeric::array arr_dist(handle_dist);
   ^
src/knn.cpp:100:3: error: 'numeric' has not been declared
   numeric::array arr_ind(handle_ind);
   ^
src/knn.cpp:105:21: error: 'arr_dist' was not declared in this scope
   return make_tuple(arr_dist.copy(), arr_ind.copy());
                     ^
src/knn.cpp:105:38: error: 'arr_ind' was not declared in this scope
   return make_tuple(arr_dist.copy(), arr_ind.copy());
                                      ^
src/knn.cpp: In function 'void init_module_knn()':
src/knn.cpp:111:3: error: 'numeric' has not been declared
   numeric::array::set_module_and_type("numpy", "ndarray");
   ^
make: *** [build/knn.o] Error 1

**Comment by houkai** [comment]
I get the same error, thanks for any reply.

**Comment by houkai** [comment]
i have solve the problem. http://www.boost.org/users/history/version_1_65_0.html
`
The boost::python::numeric API has been removed, as it is being obsoleted by boost::python::numpy.
`
change to numpy, it's worked.

**Comment by redzhepdx** [comment]
boost 1.66.0 has python:: numeric and you should you add 
`#include <boost/python/numeric.hpp>`
library to knn.cpp file.

But it works fine with 1.58

**Comment by xiaozhang404-coding** [comment]
I made an error when installing DBow2, went to the boost official website and found that boost::python::numericAPI has been removed and replaced with boost::python::numpy for boost 1.65.0 and above. But I didn't find documentation about this interface. So I downloaded "numeric.hpp", its version is boost1.64.0, but I did not install it, but added "numeric.hpp" to the header file of the source code that reported the error, and the compilation and installation passed.
